apps/catalogue/urls.py
from django.urls import path

from apps.catalogue import views

#Product
urlpatterns =[
    path('product-list', views.ProductListView.as_view(), name='ProductListView'),
    path('product-detail/<str:slug>', views.ProductDetailView.as_view(), name='ProductDetailView'),
    path('product-create', views.ProductCreateView.as_view(), name='ProductCreateView'),
]

#Product Variant
urlpatterns +=[
    path('product-variant-list', views.ProductVariantListView.as_view(), name='ProductVariantListView'),
    path('product-variant-detail/<str:pk>', views.ProductVariantDetailView.as_view(), name='ProductVariantDetailView'),
    path('product-variant-create', views.ProductVariantCreateView.as_view(), name='ProductVariantCreateView'),
]

#Attribute
urlpatterns +=[
    path('attribute-list', views.AttributeListView.as_view(), name='AttributeListView'),
    path('attribute-detail/<str:pk>',views.AttributeDetailView.as_view(), name='AttributeDetailView'),
    path('attribute-create',views.AttributeCreateView.as_view(), name='AttributeCreateView'),
]

#Attribute Value
urlpatterns +=[
    path('attribute-value-list', views.AttributeValueListView.as_view(), name='AttributeValueListView'),
    # path('attribute-value-detail/<str:pk>',views.AttributeValueDetailView.as_view(), name='AttributeValueDetailView'),
    # path('attribute-value-create',views.AttributeValueCreateView.as_view(), name='AttributeValueCreateView'),
]

ecom/urls.py
from django.urls import include, path
from django.views.i18n import JavaScriptCatalog

#API
urlpatterns = [
    path('api/auths/', include('apps.auths.urls_api')),
    path('api/catalogue/', include('apps.catalogue.urls_api')),
    path('api/accounts/', include('apps.accounts.urls_api')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

#View
urlpatterns +=[
    path('catalogue/',include('apps.catalogue.urls')),
    path('accounts/', include('apps.accounts.urls')),
]

#Health Check
urlpatterns += [
    path('api/shared/', include('apps.shared.urls')),
]

apps/catalogue/models/categories.py
from django.db import models
from apps.shared.models import BaseModelActive, BaseModelCreated, BaseModelDeleted, BaseModelInt, BaseModelUpdated
class Category(BaseModelInt, BaseModelActive, BaseModelCreated, BaseModelUpdated, BaseModelDeleted):
    name = models.CharField(max_length=100)
    sku = models.CharField(max_length=100, unique=True)
    class Meta:
        db_table = 'catalogue_product_categories'

apps/catalogue/models/collection.py
from django.db import models
class Collection(models.Model):
    name = models.CharField(max_length=100)
    sku = models.CharField(max_length=150, unique=True)
    is_deleted = models.BooleanField(default=False)

apps/catalogue/models/products.py
from django.db import models
from apps.catalogue.models.categories import Category
from apps.catalogue.models.collection import Collection
from apps.shared.models import BaseModelActive, BaseModelCreated, BaseModelDeleted, BaseModelInt, BaseModelUpdated
# Create your models here.

class Product(BaseModelInt, BaseModelActive, BaseModelCreated, BaseModelUpdated, BaseModelDeleted):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    description = models.TextField(blank=True)
    img = models.CharField(max_length=255, blank=True)
    category = models.ForeignKey(Category, db_column='category_id' , on_delete=models.RESTRICT, null=True)

    class Meta:
        db_table = 'catalogue_products'

class ProductVariant(BaseModelInt, BaseModelActive, BaseModelCreated, BaseModelUpdated, BaseModelDeleted):
    product = models.ForeignKey(Product, db_column= 'product_id', on_delete=models.RESTRICT, related_name='variants')
    name = models.CharField(max_length=100)
    img = models.CharField(max_length=255, blank=True)
    sku = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    stock_qty = models.IntegerField(default=0)

    class Meta:
        db_table = 'catalogue_product_variants'

class Attribute(BaseModelInt, BaseModelActive, BaseModelCreated, BaseModelUpdated, BaseModelDeleted):
    name = models.CharField(max_length=100)
    values = models.ManyToManyField(
        'AttributeValue',
        through='M2MAttribute',
        related_name='attributes'
    )
    class Meta:
        db_table = 'catalogue_attribute'

class AttributeValue(BaseModelInt, BaseModelActive, BaseModelCreated, BaseModelUpdated, BaseModelDeleted):
    name = models.CharField(max_length=50)
   
    class Meta:
        db_table = 'catalogue_attribute_value'

class M2MAttribute(BaseModelInt, BaseModelActive, BaseModelCreated, BaseModelUpdated, BaseModelDeleted):
    attribute = models.ForeignKey(Attribute, db_column='attribute_id', on_delete=models.RESTRICT)
    attribute_value = models.ForeignKey(AttributeValue, db_column='attribute_value_id', on_delete=models.RESTRICT)
    class Meta:
        db_table = 'catalogue_m2m_attribute'
        unique_together = ('attribute_id','attribute_value_id')

class M2MProductVarianAttribute(BaseModelInt, BaseModelActive, BaseModelCreated, BaseModelUpdated, BaseModelDeleted):
    product_variant = models.ForeignKey(ProductVariant, db_column='product_variant_id',on_delete=models.RESTRICT)
    m2m_attribute = models.ForeignKey(Attribute, db_column='m2m_attribute_id',on_delete=models.RESTRICT)

    class Meta:
        db_table = 'catalogue_m2m_product_variant_attribute'
        unique_together = ('product_variant_id', 'm2m_attribute_id')

apps/catalogue/models/promotions.py
from django.db import models
from django.utils.text import slugify

from apps.catalogue.models.categories import Category
from apps.catalogue.models.collection import Collection
from apps.catalogue.models.products import Product
class Promotion(models.Model):
    name = models.CharField(max_length= 100)
    description = models.CharField(max_length = 255, blank = True, null =True)
    slug = models.SlugField(max_length=100 ,unique=True, blank= True)
    percent = models.FloatField(null = True)
    fix_amount = models.FloatField(null = True)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField(null = True)
    is_activate = models.BooleanField(default=True)

    product = models.ManyToManyField(Product, db_column='product_id', blank=True, related_name="promotions")
    category = models.ManyToManyField(Category, db_column='category_id', blank=True, related_name="promotions")
    collection = models.ManyToManyField(Collection, db_column='collection_id', blank=True, related_name="promotions")

apps/catalogue/models/vouchers.py
from django.db import models
class Voucher(models.Model):
    voucher_code = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length= 100)
    description = models.CharField(max_length = 255, blank = True, null =True)
    percent = models.FloatField(null = True)
    fix_amount = models.FloatField(null = True)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField(null = True)
    is_activate = models.BooleanField(default=True)

apps/catalogue/views/attributes.py
from django.shortcuts import render
from django.views import View

from ..models.products import Attribute

from ...shared.decorator.views import mask_view

MASK_VIEW_CONFIG ={
    "accordion": "ecommerce",
    "accordion_child": "attribute"
}

class AttributeListView(View):
    MASK_VIEW_CONFIG_UPDATE = {
        **MASK_VIEW_CONFIG,
        "space_code": "attribute-list"
    }
    @mask_view(**MASK_VIEW_CONFIG_UPDATE)
    def get(self, request, *args, context, **kwargs):
        return render(request,'attributes/list.html', context=context)
    
class AttributeDetailView(View):
    MASK_VIEW_CONFIG_UPDATE = {
        **MASK_VIEW_CONFIG,
        "space_code": "attribute-list"
    }
    @mask_view(**MASK_VIEW_CONFIG_UPDATE)
    def get(self, request, *args, context, **kwargs):
        pk = kwargs.get('pk')
        try:
            attribute = Attribute.objects.get(pk=pk)
            attribute_values = attribute.values.all()
            context['obj_attribute'] = attribute
            context['obj_attribute_values'] = attribute_values
        except:
            return render(request,'admin/notfound/notfound.html', context=context)
        return render(request,'attributes/detail.html', context=context)
    
class AttributeCreateView(View):
    MASK_VIEW_CONFIG_UPDATE = {
        **MASK_VIEW_CONFIG,
        "space_code": "attribute-create"
    }
    @mask_view(**MASK_VIEW_CONFIG_UPDATE)
    def get(self, request, *args, context, **kwargs):
        return render(request,'attributes/create.html', context=context)
    
class AttributeValueListView(View):
    MASK_VIEW_CONFIG_UPDATE = {
        **MASK_VIEW_CONFIG,
        "space_code": "attribute-value-list"
    }
    @mask_view(**MASK_VIEW_CONFIG_UPDATE)
    def get(self, request, *args, context, **kwargs):
        return render(request,'attribute_values/list.html', context=context)

apps/catalogue/views/product_variants.py
from django.shortcuts import render
from django.views import View

from ..models.products import ProductVariant

from ...shared.decorator.views import mask_view

MASK_VIEW_CONFIG ={
    "accordion": "ecommerce",
    "accordion_child": "product-variant"
}

class ProductVariantListView(View):
    MASK_VIEW_CONFIG_UPDATE = {
        **MASK_VIEW_CONFIG,
        "space_code": "product-variant-list"
    }
    @mask_view(**MASK_VIEW_CONFIG_UPDATE)
    def get(self, request, *args, context, **kwargs):
        return render(request,'product_variants/list.html', context=context)
    
class ProductVariantDetailView(View):
    MASK_VIEW_CONFIG_UPDATE = {
        **MASK_VIEW_CONFIG,
        "space_code": "product-variant-list"
    }
    @mask_view(**MASK_VIEW_CONFIG_UPDATE)
    def get(self, request, *args, context, **kwargs):
        if 'pk' in kwargs:
            obj_product_variant = ProductVariant.objects.get(pk=kwargs.get('pk'), is_deleted = False)
            context['obj_product_variant'] = obj_product_variant
        else:
            return render(request,'admin/notfound/notfound.html', context=context)
        return render(request,'product_variants/detail.html', context=context)
    
class ProductVariantCreateView(View):
    MASK_VIEW_CONFIG_UPDATE = {
        **MASK_VIEW_CONFIG,
        "space_code": "product-variant-create"
    }
    @mask_view(**MASK_VIEW_CONFIG_UPDATE)
    def get(self, request, *args, context, **kwargs):
        return render(request,'product_variants/create.html', context=context)

apps/catalogue/views/products.py
from django.shortcuts import render
from django.views import View

from apps.catalogue.models.products import Product
from ..serializers.products import ProductDetailSerializer
from apps.shared.decorator.views import mask_view

MASK_VIEW_CONFIG ={
    "accordion": "ecommerce",
    "accordion_child": "product",
    "menu_item_show": "product"
}

class ProductListView(View):
    MASK_VIEW_CONFIG_UPDATE = {
        **MASK_VIEW_CONFIG,
        "space_code": "product-list"
    }
    @mask_view(**MASK_VIEW_CONFIG_UPDATE)
    def get(self, request, *args, context, **kwargs):
        return render(request,'products/list.html', context=context)
    
class ProductDetailView(View):
    MASK_VIEW_CONFIG_UPDATE = {
        **MASK_VIEW_CONFIG,
        "space_code": "product-list"
    }
    @mask_view(**MASK_VIEW_CONFIG_UPDATE)
    def get(self, request, *args, context, **kwargs):
        slug = kwargs.get('slug')
        try:
            product = Product.objects.get(slug=slug)
            context['obj_product'] = product
        except:
            return render(request,'admin/notfound/notfound.html', context=context)
        return render(request, 'products/detail.html', context=context)
    
class ProductCreateView(View):
    MASK_VIEW_CONFIG_UPDATE = {
        **MASK_VIEW_CONFIG,
        "space_code": "product-create"
    }
    @mask_view(**MASK_VIEW_CONFIG_UPDATE)
    def get(self, request, *args, context, **kwargs):
        return render(request, 'products/create.html', context=context)

apps/catalogue/templates/products/create.html
{% extends 'admin/base.html' %}
{% load static i18n %}
{% block head %}
{% include 'import/jquery_import.html' %}
{% include 'import/jquery_validation.html' %}
{% include 'import/toast_import.html' %}
{% include 'import/spin_import.html' %}
{% include 'import/sweetalert2_import.html' %}
{% include 'import/uppy_import.html' %}
{% include 'import/select2_import.html' %}
{% include 'import/axios_import.html' %}
{% endblock %}
{% block content %}
<div class="kt-container-fixed space-y-6">
    <form class="kt-form" id="frm_create_product" data-url-add="{% url 'ProductCreateView' %}"
        data-url-list="{% url 'ProductListView' %}" data-url-detail="{% url 'ProductDetailView' slug='__slug__' %}"
        data-url="{% url 'ProductCreateAPI' %}" data-url-upload="{% url 'UploadImageAPI' %}">
        <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
            <div class="lg:col-span-2">
                <div class="kt-card p-5 rounded-xl border bg-card">
                    <h2 class="text-lg font-semibold mb-3">Thêm sản phẩm</h2>
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div class="kt-form-item">
                            <label class="kt-form-label required" for="inp_name">{% trans 'Name' %}:</label>
                            <div class="kt-form-control">
                                <input id="inp_name" type="text" class="kt-input w-full" name="name" required />
                            </div>
                            <div class="kt-form-description"></div>
                        </div>
                        <div class="kt-form-item">
                            <label class="kt-form-label" for="inp_description">{% trans 'Description' %}:</label>
                            <div class="kt-form-control">
                                <textarea id="inp_description" class="kt-input w-full resize-y" name="description"
                                    rows="3"></textarea>
                            </div>
                            <div class="kt-form-description"></div>
                        </div>
                    </div>
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div class="kt-form-item">
                            <label class="kt-form-label" for="inp_price">{% trans 'Price' %}:</label>
                            <div class="kt-form-control">
                                <input id="inp_price" type="text" name="price" class="kt-input w-full">
                            </div>
                        </div>
                        <div class="kt-form-item">
                            <label class="kt-form-label" for="inp_is_active">{% trans 'Status' %}:</label>
                            <div class="kt-form-control">
                                <input class="kt-switch kt-switch-lg" type="checkbox" id="inp_is_active"
                                    name="is_active" checked="" />
                            </div>
                        </div>
                    </div>
                    <div class="kt-form-item mt-6">
                        <div class="flex-1 kt-form-item">
                            <label class="kt-form-label" for="image_product">
                                {% trans 'Image' %}:
                            </label>
                            <div class="kt-form-control">
                                <div id="image_product" name="image_product"></div>
                            </div>
                            <div class="kt-form-description"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="lg:col-span-1">
                <div class="kt-card p-5 rounded-xl border bg-card space-y-6">
                    <div>
                        <h2 class="text-lg font-semibold mb-3">Category</h2>
                        <div class="kt-form-item">
                            <label class="kt-form-label">Select category:</label>
                            <select id="inp_select_category" name="category" class="kt-select w-full"
                                data-url="{% url 'CategoryListAPI' %}">
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="w-full">
            {% include 'button/form-actions-no-delete.html' %}
        </div>
    </form>
</div>

{% endblock %}

{% block foot %}
<script src="{% static 'products/create.js' %}"></script>
{% endblock %}

apps/catalogue/templates/products/detail.html
{% extends 'admin/base.html' %}
{% load static i18n %}
{% block head %}
{% include 'import/jquery_import.html' %}
{% include 'import/datatable_import.html' %}
{% include 'import/jquery_validation.html' %}
{% include 'import/uppy_import.html' %}
{% include 'import/toast_import.html' %}
{% include 'import/spin_import.html' %}
{% include 'import/sweetalert2_import.html' %}
{% include 'import/select2_import.html' %}
{% include 'import/axios_import.html' %}
{% endblock %}
{% block content %}
<div class="kt-container-fixed space-y-6">
    <form class="kt-form" id="frm_detail_product" data-url="{% url 'ProductUpdateAPI' pk='__pk__' %}"
        data-url-upload="{% url 'UploadImageAPI' %}" data-url-list="{% url 'ProductListView' %}"
        data-url-delete="{% url 'ProductDestroyAPI' %}" data-url-add="{% url 'ProductCreateView' %}"
        data-url-detail="{% url 'ProductDetailView' slug='__slug__' %}">
        <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {% if obj_product %}
            <div class="lg:col-span-2">
                <div class="kt-card p-5 rounded-xl border bg-card">
                    <h2 class="text-lg font-semibold mb-3">Thông tin sản phẩm</h2>
                    <input class="hidden" id="id_product" value="{{ obj_product.id|default:'' }}">
                    <!-- Tên & Slug -->
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div class="kt-form-item">
                            <label class="kt-form-label">Tên sản phẩm:</label>
                            <input name="name" type="text" class="kt-input w-full"
                                value="{{ obj_product.name|default:'' }}">
                        </div>

                        <div class="kt-form-item">
                            <label class="kt-form-label">Slug:</label>
                            <input readonly name="slug" type="text" class="kt-input w-full"
                                value="{{ obj_product.slug|default:'' }}">
                        </div>
                    </div>
                    <div class="kt-accordion-content hidden" aria-labelledby="accordion_toggle_0"
                        id="accordion_content_0">
                        <div class="kt-accordion-wrapper">
                            <!-- Mô tả -->
                            <div class="kt-form-item mt-6">
                                <label class="kt-form-label">Mô tả:</label>
                                <input name="description" type="text" class="kt-input w-full"
                                    value="{{ obj_product.description|default:'' }}">
                            </div>

                            <!-- Giá & Trạng thái -->
                            <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-6">
                                <div class="kt-form-item">
                                    <label class="kt-form-label">Giá:</label>
                                    <div class="kt-form-control">
                                        <input id="inp_price" type="text" name="price" class="kt-input w-full"
                                            value="{{ obj_product.price|default:'0' }}" required>
                                    </div>
                                </div>
                                <div class="kt-form-item">
                                    <label class="kt-form-label">Trạng thái:</label>
                                    <input name="is_active" type="checkbox" class="kt-switch toggle-active" {% if obj_product.is_active %} checked {% endif %} />
                                </div>

                            </div>
                            <!--Hình ảnh-->
                            <div class="kt-form-item mt-6">
                                <label class="kt-form-label">Hình ảnh:</label>
                                <input type="text" id="check_image" class="hidden"
                                    value="{{ obj_product.img|default:'' }}">
                                <div class="kt-form-control">
                                    <div id="image_product" name="image_product"></div>
                                </div>
                                <div class="kt-form-description"></div>
                            </div>
                        </div>
                    </div>
                    <div data-kt-accordion="true" class="kt-accordion mt-6">
                        <div data-kt-accordion-item="true" class="kt-accordion-item">
                            <button id="accordion_toggle_0" data-kt-accordion-toggle="true"
                                aria-controls="accordion_content_0"
                                class="kt-accordion-toggle flex items-center gap-2 w-full px-6 py-3 rounded-lg bg-accent/50">

                                <!-- Text khi đóng -->
                                <span
                                    class="kt-accordion-title kt-accordion-indicator-on flex-1 text-sm font-medium ml-5">
                                    Xem thêm...
                                </span>

                                <!-- Text khi mở -->
                                <span
                                    class="kt-accordion-title kt-accordion-indicator-off flex-1 text-sm font-medium ml-5">
                                    Ẩn bớt
                                </span>

                                <!-- Icon + / - -->
                                <span aria-hidden="true" class="kt-accordion-indicator flex-shrink-0 mr-5">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"
                                        fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                        stroke-linejoin="round" class="lucide lucide-plus kt-accordion-indicator-on">
                                        <path d="M5 12h14"></path>
                                        <path d="M12 5v14"></path>
                                    </svg>

                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"
                                        fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                        stroke-linejoin="round" class="lucide lucide-minus kt-accordion-indicator-off">
                                        <path d="M5 12h14"></path>
                                    </svg>
                                </span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}

            <div>
                <div class="kt-card p-5 rounded-xl border bg-card space-y-6">
                    <div>
                        <h2 class="text-lg font-semibold mb-3">Category</h2>
                        <div class="kt-form-item">
                            <label class="kt-form-label">Select category:</label>
                            <select id="inp_select_category" name="category" class="kt-select w-full"
                                data-url="{% url 'CategoryListAPI' %}">
                                {% if obj_product.category %}
                                <option value="{{ obj_product.category.id }}" selected>
                                    {{ obj_product.category.name }}
                                </option>
                                {% endif %}
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% include 'products/extends/product_variants.html' with obj_product=obj_product %}
        <div class="w-full">
            {% include 'button/form-actions-with-delete.html' %}
        </div>
    </form>
</div>
<div>
    <form id="frm_modal_variant" data-url="{% url 'ProductVariantCreateAPI' %}"
        data-url-upload="{% url 'UploadImageAPI' %}">
        <div class="kt-modal kt-modal-center" data-kt-modal="true" id="modal_product_variant">
            <div class="kt-modal-content max-w-[70%] border-0">
                <div class="kt-modal-header border-0 bg-blue-500 rounded-t-lg">
                    <h3 class="kt-modal-title text-white">Product Variant</h3>
                    <button type="button" class="kt-modal-close text-white" aria-label="Close modal"
                        data-kt-modal-dismiss="#modal">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                            stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                            class="lucide lucide-x" aria-hidden="true">
                            <path d="M18 6 6 18"></path>
                            <path d="m6 6 12 12"></path>
                        </svg>
                    </button>
                </div>
                <div class="kt-modal-body max-h-[50vh]">
                    <input type="hidden" name="product" value="{{ obj_product.id }}">
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div class="kt-form-item">
                            <label class="kt-form-label required" for="inp_name">{% trans 'Name' %}:</label>
                            <div class="kt-form-control">
                                <input id="inp_name" type="text" class="kt-input w-full" name="name" required />
                            </div>
                            <div class="kt-form-description"></div>
                        </div>
                        <div class="kt-form-item">
                            <label class="kt-form-label required" for="inp_sku">{% trans 'SKU' %}:</label>
                            <div class="kt-form-control">
                                <input id="inp_sku" class="kt-input w-full resize-y" name="sku" required />
                            </div>
                            <div class="kt-form-description"></div>
                        </div>
                    </div>
                    <div class="grid grid-cols-3 gap-4">
                        <div class="kt-form-item">
                            <label class="kt-form-label" for="inp_price">{% trans 'Price' %}:</label>
                            <div class="kt-form-control">
                                <input id="inp_price" type="text" name="price" class="kt-input w-full" required>
                            </div>
                        </div>
                        <div class="kt-form-item">
                            <label class="kt-form-label" for="inp_stock">{% trans 'Stock' %}:</label>
                            <div class="kt-form-control">
                                <input id="inp_stock" type="number" min="0" value="0" name="stock_qty"
                                    class="kt-input w-full" required>
                            </div>
                        </div>
                        <div class="kt-form-item">
                            <label class="kt-form-label" for="inp_is_active">{% trans 'Status' %}:</label>
                            <div class="kt-form-control">
                                <input class="kt-switch kt-switch-lg" type="checkbox" id="inp_is_active"
                                    name="is_active" checked="" />
                            </div>
                        </div>
                    </div>
                    <div class="kt-form-item mt-6">
                        <label class="kt-form-label">Hình ảnh:</label>
                        <div class="kt-form-control">
                            <div id="image_product_variant"></div>
                        </div>
                        <div class="kt-form-description"></div>
                    </div>
                </div>
                <div class="kt-modal-footer gap-2.5 justify-end border-0">
                    <div class="flex gap-4">
                        <button class="kt-btn kt-btn-secondary" data-kt-modal-dismiss="#modal-variant" type="button">
                            Cancel
                        </button>
                        <button class="kt-btn" type="submit">
                            Save
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}
{% block foot %}
<script src="{% static 'products/detail.js' %}"></script>
{% endblock %}